version: "2"

services:
  odoo:
    container_name: odoo
    image: odoo:14
    restart: unless-stopped
    command: --dev=all
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    volumes:
      - ../addons/${ADDONS_REPOSITORY}/:/mnt/extra-addons
      - ../enterprise:/mnt/enterprise
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo/
      - odoo_data:/var/lib/odoo
    environment:
    - HOST=odoo_db
    - USER=odoo
    - PASSWORD=odoo

  odoo_db:
    container_name: odoo_db
    image: postgres:13
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata

volumes:
  odoo_data:
    name: odoo-web-data-${ADDONS_REPOSITORY}
  odoo_db_data:
    name: odoo-db-data-${ADDONS_REPOSITORY}
