version: "2"

services:
  web:
    container_name: odoo_15
    image: odoo:15
    restart: unless-stopped
    command: --dev=all
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./<modules-for-dev>:/mnt/<modules-for-dev>
      - ../enterprise:/mnt/enterprise
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo/
      - odoo-web-data:/var/lib/odoo
    networks:
      - odoo-dev-backend

  db:
    container_name: odoo_db_15
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-dev-backend

networks:
  odoo-dev-backend:

volumes:
  odoo-web-data:
  odoo-db-data:
