version: "2"

services:
  web:
    container_name: odoo_14
    image: odoo:14
    restart: unless-stopped
    command: --dev=all
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ../projects/Binkhabaan/odoo-bke/addons:/mnt/odoo-bke
      - ../projects/Raies/odoo-raies:/mnt/odoo-raies
      - ../enterprise-14:/mnt/enterprise
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo/
      - odoo-web-data:/var/lib/odoo
    networks: 
      - odoo-dev-backend    

  db:
    container_name: odoo_db_14
    image: postgres:13
    restart: unless-stopped
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks: 
      - odoo-dev-backend  

networks:
  odoo-dev-backend:

volumes:
  odoo-web-data:
  odoo-db-data:
