version: "2"

services:
  web:
    container_name: odoo
    image: odoo:14
    restart: unless-stopped
    command: --dev=all
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    env_file: .env  
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASS}  
    volumes:
      - ../addons/${ADDONS_REPOSITORY}/:/mnt/extra-addons
      - ../enterprise:/mnt/enterprise
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo/
      - odoo_data:/var/lib/odoo
    networks: 
      - odoo-backend    

  db:
    container_name: odoo_db
    image: postgres:13
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata
    networks: 
      - odoo-backend  

networks:
  odoo-backend:

volumes:
  odoo-web-data:
  odoo-db-data:
