version: "2"

services:
  web:
    container_name: odoo
    image: odoo:15
    restart: unless-stopped
    command: --dev=all
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ../projects/Almashriq/odoo-almashriq:/mnt/odoo-almashriq
      - ../projects/Jau Flowers/odoo-jau:/mnt/odoo-jau
      - ../enterprise:/mnt/enterprise
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo/
      - odoo-web-data:/var/lib/odoo
    networks: 
      - odoo-dev-backend    

  db:
    container_name: odoo_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks: 
      - odoo-dev-backend  

networks:
  odoo-dev-backend:

volumes:
  odoo-web-data:
  odoo-db-data:
