version: "2"

services:
  web:
    container_name: odoo
    image: odoo:14
    restart: unless-stopped
    command: --dev=all
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ../${CURRENT_PROJECT}:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo/
      - odoo-web-data:/var/lib/odoo
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
  db:
    container_name: odoo_db
    image: postgres:13
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
